version = 0.1
[default.deploy.parameters]
stack_name = "tpp-ws"
resolve_s3 = true
s3_prefix = "tpp-ws"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "ExistingBucketName=\"new-bucket-front\""
